name: GrumPHP

on: [push, pull_request]
jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.0', '8.1']
                composer-options: ['', '--prefer-lowest']
            fail-fast: false
        name: PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }} with ${{ matrix.composer-options }}
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php-versions }}
                  tools: 'composer:v2'
                  extensions: pcov, mbstring, posix
            - name: Check Versions
              run: |
                  php -v
                  php -m
                  composer --version
            - name: Get composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}
            - name: Set git variables
              run: |
                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"
            - name: Run the tests
              run: | 
                  sed -i '4 i phpVersion="${{ matrix.php-versions }}"' psalm.xml
                  php vendor/bin/grumphp run --no-interaction
              env:
                  PHP_CS_FIXER_IGNORE_ENV: 1
